name: Refactor request
description: File a refactor request
title: "[Refactor]: "
labels: ["enhancement", "triage"]
assignees:
  - gouvinb
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this refactor of general interest ?
      render: markdown
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: What approach do you suggest ?
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gouvinb/wwm-accompanist/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
