name: Refactor request
description: File a refactor request
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - gouvinb
body:
  - type: dropdown
    id: type
    attributes:
      label: Update
      description: What needs to be updated ?
      options:
        - Gradle
        - Dependencies
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Data for additional information to update such as the name of the library and its version number.
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gouvinb/wwm-accompanist/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
